#!/bin/sh

function head
{
clear
echo "*****************************************************************************"
echo " "
echo " "
}


function menu
{
echo "                           请选择操作："
echo " "
echo " "
echo "　A、挂载 EFI 分区到桌面不格式化(Fat32)"
echo " "
echo "　X、安全卸载（推出）EFI 分区"
echo " "
echo "　Q、结束安装程序"
echo " "
echo "*****************************************************************************"
read -n 1 option
}

function MountFat32
{
head
diskutil list
echo " "
echo "请输入目标磁盘的 BSD 编号："
read dn
echo " "
echo "请输入目标磁盘 disk$dn 的分区编号:"
read pt
echo " "
diskp=`echo "disk"$dn"s"$pt`
ddiskp=`echo "/dev/"$diskp`
ddisk=`echo "/dev/disk"$dn`
echo "您的“磁盘标识符”为 "$ddiskp", 是否继续? （按 y 或 n）"
read -s -n 1 q2
if [ "$q2" = "y" ]; then
    {
    echo "yes"
    }
else
    {
		echo " "
		echo "操作终止！"
		echo " "
		exit 0
    }
fi
if [ -d "/Volumes/EFI" ]; then
	echo " "
	echo " 正在进行 卸载 EFI 分区........."  
	sudo umount -f /Volumes/EFI
fi
echo " "
echo " 正在进行 挂载 EFI 分区........."  
sudo rm -rf /Volumes/EFI
sudo mkdir /Volumes/EFI
sudo mount_msdos -u 0 -g 0 $ddiskp /Volumes/EFI
echo " "
echo " "
echo "挂载 EFI 分区到桌面不格式化(Fat32)已完成！"
echo " "
}

function XEFI
{
head
echo " "
echo " 正在进行 卸载 EFI 分区........." 
sudo umount -f /Volumes/EFI
sudo rm -rf /Volumes/EFI
echo " "
echo "EFI 分区已成功卸载"
echo " "
echo "X、安全卸载（推出）EFI 分区！所有操作已完成！"
echo " "
}


function Quit
{
head

echo " "
echo " " 
echo " 　　　　　 　　　结束安装程序！"
echo " "
echo " "
echo " "
echo " "
echo " "
echo "*****************************************************************************"
exit 0
}

while [ 1 ]
do
head
menu
case $option in

a)
echo
MountFat32 ;;
x)
echo
XEFI ;;
q)
echo
Quit ;;


*)
echo " 输入错误！"
esac
echo
echo "按任意键返回主菜单"
echo
read -n 1 line
clear
done

exit


