# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Do copy files
      run: |
        rm -rf /var/www/fivge.github.io/
        mkdir /var/www/fivge.github.io/
        cp -r * /var/www/fivge.github.io/
